### ISSUE TITLE
Can't launch compiled jar

### ISSUE THREAD

**Issue by turaro** [DazedNConfused-/macata-launcher#14]
Thanks a lot for developing a launcher for Mac! Unfortunately, I was unable to compile a functional .jar to launch and test the app. I'm not experienced with Java at all so no ideas on what could have gone wrong, sorry.
The command sequence was as follows:
git clone https://github.com/DazedNConfused-/macata-launcher.git

Then in the root of cloned git:
mvn validate
mvn compile
mvn test
mvn package
mvn verify
cd target
java -jar macatalauncher-0.1.jar

The outputs of the commands are attached in the text file [compile_console.txt](https://github.com/DazedNConfused-/macata-launcher/files/10772595/compile_console.txt).
 I'm using java 19.0.2 and maven 3.9.0. The maven functions ran without any errors and with some warnings in artifact relocation (?).
The launch error is:
Error: LinkageError occurred while loading main class com.dazednconfused.catalauncher.gui.MainWindow
    java.lang.ClassFormatError: Duplicate method name "$$$getFont$$$" with signature "(Ljava.lang.String;IILjava.awt.Font;)Ljava.awt.Font;" in class file com/dazednconfused/catalauncher/gui/MainWindow

 Thanks for your attention!

**Comment by DazedNConfused-** [comment]
Howdy! Thanks for checking out my humble launcher!

So, first things first: you don't need to input so many commands in chain in order to build the project from scratch. A simple `mvn package` after pulling the codebase (assuming you have both Maven and Java correctly set up in your system) will suffice, since with Maven by specifying a lifecycle phase you are implicitly including all the others that come before (thus a `package` also `validate`s, `compile`s, `test`s, etc).

This should output a jar in the `target` directory that ought to be fully functional. I am using older tools myself (Java 11 and Maven 3.8.x), but that is not to say that newer versions shouldn't be able to compile the project just fine (and in fact they do: I did a quick switch to JDK 19.0.2 and Maven 3.9.0 and the binary was fully functional).

Now on to the error: that `$$$getFont$$$` is a method generated & injected in build time by IntelliJ's [GUI Designer](https://www.jetbrains.com/help/idea/gui-designer-basics.html). This doesn't mean that you need to use IntelliJ as your IDE in order to _build_ the project, but you will most certainly need it if you ever want to _change the GUI_ itself. You probably have seen how the GUI is structured in file pairs: a `.java` class and a `.form` class; the former being plain old Java and the later being IntelliJ's Swing tool's proprietary file.

I am mentioning all this because IntelliJ's GUI building tool, while having _lots_ of positives (like allowing a developer to prototype complex interfaces as WYSIWYG in both a fast and aesthetically pleasing fashion), is not without its pitfalls: one of the most severe being that _sometimes_ the code-generation step _misbehaves_ and you end with a dud jar that complains about a method that should be present but wasn't injected.  I have personally experienced this myself in a couple of builds (amongst hundreds that I have done so far) and the logs displayed the same exact error you attached, so I am inclined to believe you got one of these bad builds.

Even if just 1% or 0.5% of the builds are bad (numbers based entirely on personal experience so far and don't reflect any serious analysis), coming from a corporate background I normally consider such metrics _intolerable_ as builds should be fully reproducible and always output the same thing. That is not the case with IntelliJ's GUI designer however it seems, which is otherwise a very mature tool in lots of aspects, but I guess even mature software has its share of bugs 😅 

In any case, I guess a _permanent_ solution that would yield 100% reproducible builds would be to skip the code-generation by setting IntelliJ to embed the java code as I write the GUIs using the IDE, and later commit that generated code in the repository. I toyed with the idea in the past, but it polluted the classes so much that I decided I would rather _tolerate_ the sporadical bad build in favor of having clean code.

And so what should a developer do when it gets one of these _duds_? Normally a `mvn clean package` (that is, a clean rebuild) solves the problem in a practical fashion, since it is _unlikely_ (though not entirely impossible) that the code-generation step would fail twice in a row. 

Lemme know if you can run the output binary after a `mvn clean package`!

**Comment by DazedNConfused-** [comment]
Anecdotically, if you just want to play around with the launcher without making changes of your own to it, you can always download one of the pre-built binaries in the [releases](https://github.com/DazedNConfused-/macata-launcher/releases) section. All of them I have used myself in my CDDA play sessions, so they are guaranteed to work 😄

**Comment by turaro** [comment]
Thanks a lot for the detailed answer! Interestingly, I already tried "clear"-ing the build and recompiling again before writing the issue and arrived at the same result. But this time, skipping all those maven steps and just "package"-ing I got a working .jar from a clear directory. Either extremely unlucky or messing up in the maven steps I guess? 
Thanks for pointing towards the binaries too - for me it would be more convenient to just download them, yes. Cheers!
